general:
  make_dataset: False
  build_features: False
  train_model: True
  test_model: False

make_dataset:
  input_file_name: final_taxi_data
  test_size: 0.3
  save_files: True
  output_train_test_file_names:
    - train_data
    - test_data
  output_cleaned_file_name: train_data_clean
  cleaner_cols_to_check_na: None
  iqr_par: 1.5

build_features:
  input_train_data: interim/train_data_clean
  input_test_data: raw/test_data
  save_data: True
  output_file_names:
    - train_data_processed
    - test_data_processed

  pipeline_dir: pipelines

  cols_to_proceed:
    - trip_distance
    - pickup_longitude
    - pickup_latitude
    - dropoff_longitude
    - dropoff_latitude
    - fare_amount
    - pickup_datetime

  geodata:
    pickup_cols:
      - pickup_latitude
      - pickup_longitude
    dropoff_cols:
      - dropoff_latitude
      - dropoff_longitude

  clusters_location:
    n_clusters: 15
    force_retrain: False
    model_dir: cluster_districts
    token: pk.eyJ1IjoiZHhrMDExMSIsImEiOiJjbG5rMnZiMWcwajR4MmpzMzBtbWh4MzUxIn0.Awp5L80wu7nmpdGvOoCunw
    geodata_columns:
      pickup_cols:
        - pickup_longitude
        - pickup_latitude
      dropoff_cols:
        - dropoff_longitude
        - dropoff_latitude

  clusters_trip:
    n_clusters: 45
    force_retrain: False
    model_dir: trip_districts
    token: pk.eyJ1IjoiZHhrMDExMSIsImEiOiJjbG5rMnZiMWcwajR4MmpzMzBtbWh4MzUxIn0.Awp5L80wu7nmpdGvOoCunw
    clustering_columns:
      - pickup_longitude
      - pickup_latitude
      - dropoff_longitude
      - dropoff_latitude

  trip_distance_model:
    force_retrain: False
    model_dir: trip_distance
    model_max_depth: 16
    grid_search_parameters:
      n_estimators: [ 50, 100, 200 ]
      max_depth: [ 4, 8, 16, 32 ]
      min_samples_leaf: [ 2, 4, 8 ]
    model_columns: # pay attention, columns from other processing step!
      - pickup_longitude
      - pickup_latitude
      - dropoff_longitude
      - dropoff_latitude
      - distance_braycurtis
      - distance_chebyshev
      - distance_cityblock
      - distance_cosine
      - distance_euclidean
      - distance_sqeuclidean
      - distance_haversine

train_model:
  optim_iters: 10
  cv_splits: 3
  parameters:
    LGBM:
      num_leaves:
        min: 20
        max: 50
      max_depth: [ -1, 3, 5, 10 ]
      learning_rate:
        min: 0.001
        max: 0.5
      n_estimators:
        min: 30
        max: 250
    CB:
      max_depth:
        min: 2
        max: 10
      learning_rate:
        min: 0.001
        max: 0.5
      n_estimators:
        min: 30
        max: 250
  model_columns:
    - pickup_longitude
    - pickup_latitude
    - dropoff_longitude
    - dropoff_latitude
    - pickup_datetime
    - distance_braycurtis
    - distance_chebyshev
    - distance_cityblock
    - distance_cosine
    - distance_euclidean
    - distance_sqeuclidean
    - distance_haversine
    - dt_month
    - dt_weekday
    - dt_isweekend
    - dt_hour
    - dt_quarter
    - dt_day_part
    - dt_isusholiday
    - dt_paydays
    - dropoff_cluster
    - pickup_cluster
    - trip_info_cluster
    - trip_distance_prediction
    - fare_amount
