general:
  make_dataset: True
  build_features: True
  train_model: True
  test_model: False

make_dataset:
  input_file_name: final_taxi_data
  test_size: 0.3
  save_files: True
  output_train_test_file_names:
    - train_data
    - test_data
  output_cleaned_file_name: train_data_clean
  cleaner_cols_to_check_na: None
  iqr_par: 1.5

build_features:
  input_train_data: interim/train_data_clean
  input_test_data: raw/test_data
  save_data: True
  output_file_names:
    - train_data_processed
    - test_data_processed

  cols_to_drop:
    - passenger_count
    - trip_distance
    - ratecodeid
    - store_and_fwd_flag
    - extra
    - mta_tax
    - tip_amount
    - tolls_amount
    - total_amount
    - vendor_id
    - dropoff_datetime
    - imp_surcharge
  pipeline_dir: pipelines

  geodata:
    pickup_cols:
      - pickup_latitude
      - pickup_longitude
    dropoff_cols:
      - dropoff_latitude
      - dropoff_longitude

  clusters_location:
    n_clusters: 15
    force_retrain: False
    model_dir: cluster_districts
    token: pk.eyJ1IjoiZHhrMDExMSIsImEiOiJjbG5rMnZiMWcwajR4MmpzMzBtbWh4MzUxIn0.Awp5L80wu7nmpdGvOoCunw
    geodata_columns:
      pickup_cols:
        - pickup_longitude
        - pickup_latitude
      dropoff_cols:
        - dropoff_longitude
        - dropoff_latitude

  clusters_trip:
    n_clusters: 45
    force_retrain: False
    model_dir: trip_districts
    token: pk.eyJ1IjoiZHhrMDExMSIsImEiOiJjbG5rMnZiMWcwajR4MmpzMzBtbWh4MzUxIn0.Awp5L80wu7nmpdGvOoCunw
    clustering_columns:
      - pickup_longitude
      - pickup_latitude
      - dropoff_longitude
      - dropoff_latitude